# Generated by Django 2.2.3 on 2020-05-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wrdcloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.FileField(upload_to='cloud/text/')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='cloud/image/')),
            ],
        ),
    ]
