# Generated by Django 2.2.3 on 2020-05-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20200518_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simple',
            name='cloud',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='wrdcloud',
            name='cloud',
            field=models.CharField(default='', max_length=20),
        ),
    ]
